# Generated by Django 2.1.4 on 2018-12-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='fundo',
            field=models.ImageField(default=1, upload_to='imagens/temas', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
