# Generated by Django 2.1.4 on 2018-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181208_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='fundo',
            field=models.ImageField(null=True, upload_to='imagens/temas', verbose_name='Imagem'),
        ),
    ]
