# Generated by Django 2.1.4 on 2018-12-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181208_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='documento',
        ),
    ]
