# Generated by Django 2.1.4 on 2018-12-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_denuncia_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='verificada',
            field=models.CharField(choices=[('Em Análise', 'Em Análise'), ('Rejeitada', 'Rejeitada'), ('Aceita', 'Aceita')], default='Em Análise', max_length=19),
        ),
    ]
