# Generated by Django 2.1.4 on 2018-12-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_denuncia_verificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
